[project]
name = "sudal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ato>=2.2.0",
    "langchain>=1.2.2",
    "langgraph>=1.0.5",
    "pydantic>=2.12.5",
]
